# Generated by Django 5.0.2 on 2024-02-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.FloatField(),
        ),
    ]
