# Generated by Django 5.0.2 on 2024-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_alter_album_description_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music_files/'),
        ),
    ]
